
name: Petclinic

on: 
  push:
     branches:
     - master


jobs:
 Test-petclinic:
    runs-on: ubuntu-latest
    container: springcommunity/spring-petclinic-rest:latest
    
    services:

       redis:
  
          image: redis
          ports: 
            - 9966:9966
 
