name: Petclinic

on:
  push:
    branches:
      - master


jobs:
  Test-petclinic:
    runs-on: ubuntu-latest
    
   
   
    services:
      redis:
        image: springcommunity/spring-petclinic-rest:latest
        ports: 
         - 9966:9966
    container: 
        image: postgres:9.6.0
        credentials:
               username: postgres-petclinic
               password: petclinic
          
        ports: 
         - 5432:5432
   
   
    

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'



      
      - run: gradle test
