
name: Petclinic

on: 
  push:
     branches:
     - master


jobs:
 Test-petclinic:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1 
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: docker://springcommunity/spring-petclinic-rest
           
      - run: docker run --name postgres-petclinic -e POSTGRES_PASSWORD=petclinic -e POSTGRES_DB=petclinic -p 5432:5432 -d postgres:9.6.0
    
    
      
      - name: Build with Gradle
      - run: ./gradlew test
