
name: CI

on: 
  push:
     branches:
     - master


jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1 
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: |
         docker run -p 9966:9966 springcommunity/spring-petclinic-rest
         docker run --name postgres-petclinic -e POSTGRES_PASSWORD=petclinic -e POSTGRES_DB=petclinic -p 5432:5432 -d postgres:9.6.0
         gradle test
         
